version: '2.3'

# ip map:
#   ipfsA     --> 172.168.10.10
#   node0     --> 172.168.10.2
#   node1     --> 172.168.10.3
#   node2     --> 172.168.10.4
#   node3     --> 172.168.10.5
#   trainer0  --> 172.168.10.50
#   trainer1  --> 172.168.10.51
#   trainer2  --> 172.168.10.52
#   trainer3  --> 172.168.10.53
#   agg       --> 172.168.10.100
#
services:
  ipfsA:
    image: tony92151/ipfs-alpine
    container_name: ipfsA
    ports:
      - 4001:4001
      - 5001:5001
    environment:
      #LIBP2P_FORCE_PNET: "true"
      HOSTIP: 172.168.10.10
      IPFS_PATH: /root/ipfs
      
    volumes: # default path : /data/ipfs/swarm.key
      # - ./ipfskey:/data/ipfs/ 
      - ./ipfs:/root
      # - ipfscon:/ipfscon
    entrypoint: /bin/bash
    command: /root/ipfsentrypoint.sh
    networks:
      localnet:
        ipv4_address: 172.168.10.10

##################################################
##################################################
  node0:
    image: tony92151/tendermint-docker
    container_name: node0
    ports:
      - "26656-26657:26656-26657"
    environment:
      - MODE=nodeapp
      - ID=0
    volumes:
      - ./script:/root
      - ./nodes:/tendermint
    entrypoint: /bin/bash
    command: /root/entrypoint.sh
    networks:
      localnet:
        ipv4_address: 172.168.10.2

  trainer0:
    image: tony92151/isltrainer-gpu
    container_name: trainer0
    runtime: nvidia
    environment:
      - MODE=trainer
      - ID=0
      - DATASET=emnist
      - NVIDIA_VISIBLE_DEVICES=0
    volumes:
      - ./script/trainer:/root
      - ./data:/mountdata
    entrypoint: /bin/bash
    command: /root/trainerentrypoint.sh
    networks:
      localnet:
        ipv4_address: 172.168.10.50

##################################################
##################################################
  node1:
    image: tony92151/tendermint-docker
    container_name: node1
    ports:
      - "26661-26662:26656-26657"
    environment:
      - MODE=nodeapp
      - ID=1
    volumes:
      - ./script:/root
      - ./nodes:/tendermint
    entrypoint: /bin/bash
    command: /root/entrypoint.sh
    networks:
      localnet:
        ipv4_address: 172.168.10.3

  trainer1:
    image: tony92151/isltrainer
    container_name: trainer1
    runtime: nvidia
    environment:
      - MODE=trainer
      - ID=1
      - DATASET=emnist
      - NVIDIA_VISIBLE_DEVICES=0
    volumes:
      - ./script/trainer:/root
      - ./data:/mountdata
    entrypoint: /bin/bash
    command: /root/trainerentrypoint.sh
    networks:
      localnet:
        ipv4_address: 172.168.10.51

##################################################
##################################################
  node2:
    image: tony92151/tendermint-docker
    container_name: node2
    ports:
      - "26663-26664:26656-26657"
    environment:
      - MODE=nodeapp
      - ID=2
    volumes:
      - ./script:/root
      - ./nodes:/tendermint
    entrypoint: /bin/bash
    command: /root/entrypoint.sh
    networks:
      localnet:
        ipv4_address: 172.168.10.4

  trainer2:
    image: tony92151/isltrainer
    container_name: trainer2
    runtime: nvidia
    environment:
      - MODE=trainer
      - ID=2
      - DATASET=emnist
      - NVIDIA_VISIBLE_DEVICES=0
    volumes:
      - ./script/trainer:/root
      - ./data:/mountdata
    entrypoint: /bin/bash
    command: /root/trainerentrypoint.sh
    networks:
      localnet:
        ipv4_address: 172.168.10.52

##################################################
##################################################
  node3:
    image: tony92151/tendermint-docker
    container_name: node3
    ports:
      - "26665-26666:26656-26657"
    environment:
      - MODE=nodeapp
      - ID=3
    volumes:
      - ./script:/root
      - ./nodes:/tendermint
    entrypoint: /bin/bash
    command: /root/entrypoint.sh
    networks:
      localnet:
        ipv4_address: 172.168.10.5

  trainer3:
    image: tony92151/isltrainer
    container_name: trainer3
    runtime: nvidia
    environment:
      - MODE=trainer
      - ID=3
      - DATASET=emnist
      - NVIDIA_VISIBLE_DEVICES=0
    volumes:
      - ./script/trainer:/root
      - ./data:/mountdata
    entrypoint: /bin/bash
    command: /root/trainerentrypoint.sh
    networks:
      localnet:
        ipv4_address: 172.168.10.53

##################################################
  agg:
    image: tony92151/isltrainer
    container_name: agg
    environment:
      - MODE=agg
      - ID=0
    volumes:
      - ./script/aggregator:/root
    entrypoint: /bin/bash
    command: /root/aggregatorentrypoint.sh
    networks:
      localnet:
        ipv4_address: 172.168.10.100

##################################################
  trainer0-gpu:
      image: tony92151/isltrainer-gpu
      container_name: trainer0-gpu
      runtime: nvidia
      environment:
        - MODE=trainer
        - ID=0
        - DATASET=emnist
      volumes:
        - ./script/trainer:/root
        - ./data:/mountdata
      deploy:
        resources:
          reservations:
            generic_resources:
              - discrete_resource_spec:
                  kind: 'gpu'
                  value: 1
      entrypoint: /bin/bash
      command: /root/trainerentrypoint.sh
      networks:
        localnet:
          ipv4_address: 172.168.10.50
  trainer1-gpu:
      image: tony92151/isltrainer-gpu
      container_name: trainer1-gpu
      runtime: nvidia
      environment:
        - MODE=trainer
        - ID=1
        - DATASET=emnist
      volumes:
        - ./script/trainer:/root
        - ./data:/mountdata
      deploy:
        resources:
          reservations:
            generic_resources:
              - discrete_resource_spec:
                  kind: 'gpu'
                  value: 1
      entrypoint: /bin/bash
      command: /root/trainerentrypoint.sh
      networks:
        localnet:
          ipv4_address: 172.168.10.51

  trainer2-gpu:
      image: tony92151/isltrainer-gpu
      container_name: trainer2-gpu
      runtime: nvidia
      environment:
        - MODE=trainer
        - ID=2
        - DATASET=emnist
      volumes:
        - ./script/trainer:/root
        - ./data:/mountdata
      deploy:
        resources:
          reservations:
            generic_resources:
              - discrete_resource_spec:
                  kind: 'gpu'
                  value: 2
      entrypoint: /bin/bash
      command: /root/trainerentrypoint.sh
      networks:
        localnet:
          ipv4_address: 172.168.10.52

  trainer3-gpu:
      image: tony92151/isltrainer-gpu
      container_name: trainer3-gpu
      runtime: nvidia
      environment:
        - MODE=trainer
        - ID=3
        - DATASET=emnist
      volumes:
        - ./script/trainer:/root
        - ./data:/mountdata
      deploy:
        resources:
          reservations:
            generic_resources:
              - discrete_resource_spec:
                  kind: 'gpu'
                  value: 2
      entrypoint: /bin/bash
      command: /root/trainerentrypoint.sh
      networks:
        localnet:
          ipv4_address: 172.168.10.53

##################################################

# volumes:
#     ipfscon:

networks:
  localnet:
    #driver: bridge
    ipam:
      #driver: default
      config:
      -
        subnet: 172.168.10.0/24
        #gateway: 172.168.10.1
