version: '3'

services:
  ipfsA:
    image: tony92151/ipfs-alpine
    container_name: ipfsA
    ports:
      - 4001:4001
      - 5001:5001
    environment:
      #LIBP2P_FORCE_PNET: "true"
      HOSTIP: 172.168.10.10
      IPFS_PATH: /root/ipfs
      
    volumes: # default path : /data/ipfs/swarm.key
      # - ./ipfskey:/data/ipfs/ 
      - ./ipfs:/root
      # - ipfscon:/ipfscon
    entrypoint: /bin/bash
    command: /root/ipfsentrypoint.sh
    networks:
      localnet:
        ipv4_address: 172.168.10.10

##################################################
  node0:
    image: tony92151/tendermint-docker
    container_name: node0
    ports:
      - "26656-26657:26656-26657"
    environment:
      - MODE=nodeapp
      - ID=0
    volumes:
      - ./script:/root
      - ./nodes:/tendermint
    entrypoint: /bin/bash
    command: /root/entrypoint.sh
    networks:
      localnet:
        ipv4_address: 172.168.10.2

##################################################
  node1:
    image: tony92151/tendermint-docker
    container_name: node1
    ports:
      - "26661-26662:26656-26657"
    environment:
      - MODE=nodeapp
      - ID=1
    volumes:
      - ./script:/root
      - ./nodes:/tendermint
    entrypoint: /bin/bash
    command: /root/entrypoint.sh
    networks:
      localnet:
        ipv4_address: 172.168.10.3

##################################################
  node2:
    image: tony92151/tendermint-docker
    container_name: node2
    ports:
      - "26663-26664:26656-26657"
    environment:
      - MODE=nodeapp
      - ID=2
    volumes:
      - ./script:/root
      - ./nodes:/tendermint
    entrypoint: /bin/bash
    command: /root/entrypoint.sh
    networks:
      localnet:
        ipv4_address: 172.168.10.4

##################################################
  node3:
    image: tony92151/tendermint-docker
    container_name: node3
    ports:
      - "26665-26666:26656-26657"
    environment:
      - MODE=nodeapp
      - ID=3
    volumes:
      - ./script:/root
      - ./nodes:/tendermint
    entrypoint: /bin/bash
    command: /root/entrypoint.sh
    networks:
      localnet:
        ipv4_address: 172.168.10.5

# volumes:
#     ipfscon:

networks:
  localnet:
    #driver: bridge
    ipam:
      #driver: default
      config:
      -
        subnet: 172.168.10.0/24
        #gateway: 172.168.10.1
