version: '3'

services:
  node0:
    image: tony92151/tendermint-docker
    container_name: node0
    ports:
      - "26656-26657:26656-26657"
    environment:
      - MODE=nodeapp
      - ID=0
    volumes:
      - ./script:/root
      - ./nodes:/tendermint
    entrypoint: /bin/bash
    command: /root/entrypoint.sh
    networks:
      localnet:
        ipv4_address: 172.168.10.2

  # abci0:
  #   container_name: abci0
  #   image: tony92151/tendermint-docker
  #   environment:
  #     - MODE=app
  #     - ID=0
  #   volumes:
  #     - ./script:/root
  #     - ./nodes:/tendermint
  #   entrypoint: /bin/bash
  #   command: /root/entrypoint.sh
  #   networks:
  #     localnet:
  #       ipv4_address: 172.168.10.6
##################################################
  node1:
    image: tony92151/tendermint-docker
    container_name: node1
    ports:
      - "26661-26662:26656-26657"
    environment:
      - MODE=nodeapp
      - ID=1
    volumes:
      - ./script:/root
      - ./nodes:/tendermint
    entrypoint: /bin/bash
    command: /root/entrypoint.sh
    networks:
      localnet:
        ipv4_address: 172.168.10.3

  # abci1:
  #   container_name: abci1
  #   image: tony92151/tendermint-docker
  #   environment:
  #     - MODE=app
  #     - ID=1
  #   volumes:
  #     - ./script:/root
  #     - ./nodes:/tendermint
  #   entrypoint: /bin/bash
  #   command: /root/entrypoint.sh
  #   networks:
  #     localnet:
  #       ipv4_address: 172.168.10.7
##################################################
  node2:
    image: tony92151/tendermint-docker
    container_name: node2
    ports:
      - "26663-26664:26656-26657"
    environment:
      - MODE=nodeapp
      - ID=2
    volumes:
      - ./script:/root
      - ./nodes:/tendermint
    entrypoint: /bin/bash
    command: /root/entrypoint.sh
    networks:
      localnet:
        ipv4_address: 172.168.10.4

  # abci2:
  #   container_name: abci2
  #   image: tony92151/tendermint-docker
  #   environment:
  #     - MODE=app
  #     - ID=2
  #   volumes:
  #     - ./script:/root
  #     - ./nodes:/tendermint
  #   entrypoint: /bin/bash
  #   command: /root/entrypoint.sh
  #   networks:
  #     localnet:
  #       ipv4_address: 172.168.10.8
##################################################
  node3:
    image: tony92151/tendermint-docker
    container_name: node3
    ports:
      - "26665-26666:26656-26657"
    environment:
      - MODE=nodeapp
      - ID=3
    volumes:
      - ./script:/root
      - ./nodes:/tendermint
    entrypoint: /bin/bash
    command: /root/entrypoint.sh
    networks:
      localnet:
        ipv4_address: 172.168.10.5

  # abci3:
  #   container_name: abci3
  #   image: tony92151/tendermint-docker
  #   environment:
  #     - MODE=app
  #     - ID=3
  #   volumes:
  #     - ./script:/root
  #     - ./nodes:/tendermint
  #   entrypoint: /bin/bash
  #   command: /root/entrypoint.sh
  #   networks:
  #     localnet:
  #       ipv4_address: 172.168.10.9



networks:
  localnet:
    #driver: bridge
    ipam:
      #driver: default
      config:
      -
        subnet: 172.168.10.0/16
        #gateway: 172.168.10.1
