// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.6.1
// source: proto/trainer.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TrainInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Round     int32  `protobuf:"varint,1,opt,name=Round,proto3" json:"Round,omitempty"`
	BaseModel string `protobuf:"bytes,2,opt,name=BaseModel,proto3" json:"BaseModel,omitempty"`
}

func (x *TrainInfo) Reset() {
	*x = TrainInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_trainer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrainInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainInfo) ProtoMessage() {}

func (x *TrainInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trainer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainInfo.ProtoReflect.Descriptor instead.
func (*TrainInfo) Descriptor() ([]byte, []int) {
	return file_proto_trainer_proto_rawDescGZIP(), []int{0}
}

func (x *TrainInfo) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *TrainInfo) GetBaseModel() string {
	if x != nil {
		return x.BaseModel
	}
	return ""
}

type TrainResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Round  int32  `protobuf:"varint,1,opt,name=Round,proto3" json:"Round,omitempty"`
	Result string `protobuf:"bytes,2,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *TrainResult) Reset() {
	*x = TrainResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_trainer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrainResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainResult) ProtoMessage() {}

func (x *TrainResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trainer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainResult.ProtoReflect.Descriptor instead.
func (*TrainResult) Descriptor() ([]byte, []int) {
	return file_proto_trainer_proto_rawDescGZIP(), []int{1}
}

func (x *TrainResult) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *TrainResult) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_proto_trainer_proto protoreflect.FileDescriptor

var file_proto_trainer_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x3f, 0x0a, 0x09, 0x54, 0x72, 0x61,
	0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x1c, 0x0a, 0x09,
	0x42, 0x61, 0x73, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x42, 0x61, 0x73, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x3b, 0x0a, 0x0b, 0x54, 0x72,
	0x61, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x6f, 0x75,
	0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x34, 0x0a, 0x07, 0x54, 0x72, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x12, 0x29, 0x0a, 0x05, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x12, 0x0d, 0x2e, 0x70, 0x62,
	0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x0f, 0x2e, 0x70, 0x62, 0x2e,
	0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_trainer_proto_rawDescOnce sync.Once
	file_proto_trainer_proto_rawDescData = file_proto_trainer_proto_rawDesc
)

func file_proto_trainer_proto_rawDescGZIP() []byte {
	file_proto_trainer_proto_rawDescOnce.Do(func() {
		file_proto_trainer_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_trainer_proto_rawDescData)
	})
	return file_proto_trainer_proto_rawDescData
}

var file_proto_trainer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_trainer_proto_goTypes = []interface{}{
	(*TrainInfo)(nil),   // 0: pb.TrainInfo
	(*TrainResult)(nil), // 1: pb.TrainResult
}
var file_proto_trainer_proto_depIdxs = []int32{
	0, // 0: pb.Trainer.Train:input_type -> pb.TrainInfo
	1, // 1: pb.Trainer.Train:output_type -> pb.TrainResult
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_trainer_proto_init() }
func file_proto_trainer_proto_init() {
	if File_proto_trainer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_trainer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrainInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_trainer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrainResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_trainer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_trainer_proto_goTypes,
		DependencyIndexes: file_proto_trainer_proto_depIdxs,
		MessageInfos:      file_proto_trainer_proto_msgTypes,
	}.Build()
	File_proto_trainer_proto = out.File
	file_proto_trainer_proto_rawDesc = nil
	file_proto_trainer_proto_goTypes = nil
	file_proto_trainer_proto_depIdxs = nil
}
